package tn.edu.esprit.sigma.controllers;

import java.net.URL;
import java.util.ArrayList;
import java.util.List;
import java.util.ResourceBundle;

import javax.persistence.EnumType;

import entities.Flight;
import entities.FlightCategory;
import entities.Passenger;
import entities.Ticket;
import javafx.event.ActionEvent;
import javafx.fxml.FXML;
import javafx.fxml.Initializable;
import javafx.scene.control.Button;
import javafx.scene.control.ComboBox;
import javafx.scene.control.Menu;
import javafx.scene.control.MenuItem;
import javafx.scene.control.TextField;
import tn.edu.esprit.sigma.client.delegate.FlightServicesDelegate;
import tn.edu.esprit.sigma.client.delegate.TicketServicesDelegate;
import tn.edu.esprit.sigma.utils.ControlledScreen;
import tn.edu.esprit.sigma.utils.ScreensController;

public class BookAFlightController implements Initializable, ControlledScreen {
	@FXML
	private Menu btn_home;
	@FXML
	private MenuItem btn_showFlights;
	@FXML
	private MenuItem btn_meals;
	@FXML
	private MenuItem btn_car;
	@FXML
	private MenuItem btn_register;
	@FXML
	private Menu btn_maps;
	@FXML
	private Menu btn_about;
	@FXML
	private ComboBox cbx_FlightCategorie;
	@FXML
	private ComboBox cbx_Flight;
	@FXML
	private TextField txt_price;
	@FXML
	private TextField txt_firstName;
	@FXML
	private TextField txt_LastName;
	@FXML
	private TextField txt_BirtDate;
	@FXML
	private TextField txt_gender;
	@FXML
	private TextField txt_Email;
	@FXML
	private TextField txt_PhoneNumber;
	@FXML
	private Button btn_ticket;

	// Event Listener on Menu[#btn_home].onAction
	@FXML
	public void showHome(ActionEvent event) {
		// TODO Autogenerated
	}

	// Event Listener on MenuItem[#btn_showFlights].onAction
	@FXML
	public void showFlights(ActionEvent event) {
		// TODO Autogenerated
	}

	// Event Listener on MenuItem[#btn_meals].onAction
	@FXML
	public void showMeals(ActionEvent event) {
		// TODO Autogenerated
	}

	// Event Listener on MenuItem[#btn_car].onAction
	@FXML
	public void showCar(ActionEvent event) {
		// TODO Autogenerated
	}

	// Event Listener on MenuItem[#btn_register].onAction
	@FXML
	public void Register(ActionEvent event) {
		// TODO Autogenerated
	}

	// Event Listener on MenuItem.onAction
	@FXML
	public void showMapAirport(ActionEvent event) {
		// TODO Autogenerated
	}

	// Event Listener on Menu[#btn_about].onAction
	@FXML
	public void showAbout(ActionEvent event) {
		// TODO Autogenerated
	}

	

	// Event Listener on Button[#btn_ticket].onAction
	@FXML
	public void generateTicket(ActionEvent event) {
		Passenger p =AuthentificateController.passenger;
		TicketServicesDelegate delegate =new TicketServicesDelegate();
		Flight t = (Flight) cbx_Flight.getSelectionModel().getSelectedItem();
//		Ticket ticket1 = TicketServicesDelegate.doFindTicketByFlightIdAndPassengerIdd(p.getId(), t.getId());
//		txt_price.setText(Float.valueOf(ticket1.getPrice()).toString());
		
		List<FlightCategory> categories = new ArrayList<>();
		
		Flight F =(Flight) cbx_Flight.getSelectionModel().getSelectedItem();
		
		txt_price.setText(Float.valueOf(F.getPriceMap().toString()) .toString()
				);
					
		 
		if(delegate.doBookTicketBis(p.getId(), t.getId(), (FlightCategory) cbx_FlightCategorie.getSelectionModel().getSelectedItem())){
			
			{System.out.println("ok");}
		
		
	
	}
	}

	@Override
	public void SetScreenParent(ScreensController screenpage) {
		// TODO Auto-generated method stub

	}

	@Override
	public void initialize(URL location, ResourceBundle resources) {

Passenger p =AuthentificateController.passenger;

txt_firstName.setDisable(true);
txt_firstName.setText(p.getFirstName());

txt_LastName.setDisable(true);
txt_LastName.setText(p.getLastName());

txt_BirtDate.setDisable(true);
txt_BirtDate.setText(p.getBirthDate().toString());

txt_Email.setDisable(true);
txt_Email.setText(p.getEmail().toString());

txt_PhoneNumber.setDisable(true);
txt_PhoneNumber.setText(Integer.valueOf(p.getPhoneNumber().toString()).toString());

txt_gender.setDisable(true);
txt_gender.setText(p.getSexe().toString());
txt_price.setDisable(true);

FlightServicesDelegate flightServicesDelegate = new FlightServicesDelegate();



cbx_Flight.getItems().addAll(flightServicesDelegate.doFindAllFlights());
Flight t = (Flight) cbx_Flight.getSelectionModel().getSelectedItem();

cbx_FlightCategorie.getItems().addAll(FlightCategory.values());

FlightCategory category =(FlightCategory) cbx_FlightCategorie.getSelectionModel().getSelectedItem();





		
		
		



		
	}
}
