package tn.edu.esprit.sigma.controllers;

import javafx.fxml.FXML;
import javafx.fxml.Initializable;
import javafx.scene.control.Button;

import javafx.scene.control.TextField;
import javafx.scene.control.cell.PropertyValueFactory;
import javafx.scene.input.MouseEvent;
import tn.edu.esprit.sigma.client.delegate.CarServicesDelegate;
import tn.edu.esprit.sigma.client.delegate.FlightServicesDelegate;
import tn.edu.esprit.sigma.utils.ControlledScreen;
import tn.edu.esprit.sigma.utils.Main;
import tn.edu.esprit.sigma.utils.ScreensController;

import java.net.URL;
import java.util.ArrayList;
import java.util.ResourceBundle;

import entities.Car;
import entities.Flight;
import javafx.collections.FXCollections;
import javafx.collections.ObservableList;
import javafx.event.ActionEvent;

import javafx.scene.control.MenuItem;

import javafx.scene.control.TableView;

import javafx.scene.control.Menu;

import javafx.scene.control.TableColumn;

public class CarController implements Initializable , ControlledScreen{
	@FXML
	private Menu btn_home;
	@FXML
	private MenuItem btn_showFlights;
	@FXML
	private MenuItem btn_meals;
	@FXML
	private MenuItem btn_car;
	@FXML
	private MenuItem btn_register;
	@FXML
	private Menu btn_maps;
	@FXML
	private Menu btn_about;
	@FXML
	private TextField txt_registrationNumber;
	@FXML
	private TextField txt_brand;
	@FXML
	private TextField txt_category;
	@FXML
	private TextField txt_description;
	@FXML
	private TextField txt_price;
	@FXML
	private Button btn_ticket;
	@FXML
	private TableView tbl_car;
	@FXML
	private TableColumn cl_regis;
	@FXML
	private TableColumn cl_brand;
	@FXML
	private TableColumn cl_gategory;
	@FXML
	private TableColumn cl_descrip;
	@FXML
	private TableColumn cl_price;
	@FXML
	private Button btn_update;
	@FXML
	private Button btn_delete;

	int id=0;
	
	// Event Listener on Menu[#btn_home].onAction
	@FXML
	public void showHome(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on MenuItem[#btn_showFlights].onAction
	@FXML
	public void showFlights(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on MenuItem[#btn_meals].onAction
	@FXML
	public void showMeals(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on MenuItem[#btn_car].onAction
	@FXML
	public void showCar(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on MenuItem[#btn_register].onAction
	@FXML
	public void Register(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on MenuItem.onAction
	@FXML
	public void showMapAirport(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Menu[#btn_about].onAction
	@FXML
	public void showAbout(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btn_ticket].onAction
	@FXML
	public void generateTicket(ActionEvent event) {
		Car car= new Car();
		car.setRegistrationNumber(txt_registrationNumber.getText());
		car.setPrice(Float.valueOf(txt_price.getText().toString()));
		car.setDescription(txt_description.getText());
		car.setBrand(txt_brand.getText());
//		car.setCategory(txt_category.getText());
		CarServicesDelegate.doAddCar(car);
		Main.mainCantainer.loadscreen(Main.g_carID, Main.g_carFile);
		Main.mainCantainer.setScreen(Main.g_carID);
	}
	// Event Listener on Button[#btn_update].onAction
	@FXML
	public void update(ActionEvent event) {
		
		int id=((Car) tbl_car.getSelectionModel().getSelectedItem()).getId();
	Car c=	CarServicesDelegate.doFindCarById(id);
		txt_registrationNumber.setText(c.getRegistrationNumber());
		txt_price.setText(String.valueOf(c.getPrice()));
		txt_description.setText(c.getDescription());
		txt_brand.setText(c.getBrand());
//		car.setCategory(txt_category.getText());
		CarServicesDelegate.doUpdateCar(c);
		Main.mainCantainer.loadscreen(Main.g_carID, Main.g_carFile);
		Main.mainCantainer.setScreen(Main.g_carID);
	}
	// Event Listener on Button[#btn_delete].onAction
	@FXML
	public void delete(ActionEvent event) {
		int id=((Car) tbl_car.getSelectionModel().getSelectedItem()).getId();
		Car c=	CarServicesDelegate.doFindCarById(id);
		CarServicesDelegate.doDeleteCar(c);
		Main.mainCantainer.loadscreen(Main.g_carID, Main.g_carFile);
		Main.mainCantainer.setScreen(Main.g_carID);
	}
	@Override
	public void SetScreenParent(ScreensController screenpage) {
		// TODO Auto-generated method stub
		
	}
	@FXML
	public void selectId(MouseEvent event){
		if(event.getClickCount()>0){
			if (tbl_car.getSelectionModel().getSelectedIndex()>=0){}
		
	}
	}
	@Override
	public void initialize(URL location, ResourceBundle resources) {
		ArrayList<Car> cars = (ArrayList<Car>) CarServicesDelegate.doFindAllCars();
		ObservableList<Car> data = FXCollections.observableArrayList(cars);
		for (Car car : cars) {
			cl_regis.setCellValueFactory(new PropertyValueFactory<Flight, String>("registrationNumber"));
			cl_brand.setCellValueFactory(new PropertyValueFactory<Flight, String>("brand"));
			cl_gategory.setCellValueFactory(new PropertyValueFactory<Flight, String>("category"));
			cl_descrip.setCellValueFactory(new PropertyValueFactory<Flight, String>("description"));
			cl_price.setCellValueFactory(new PropertyValueFactory<Flight, String>("price"));
			tbl_car.setItems(data);
		}
		
	}
}
