package tn.edu.esprit.sigma.controllers;

import java.net.URL;
import java.util.ArrayList;
import java.util.ResourceBundle;

import entities.Flight;
import javafx.collections.FXCollections;
import javafx.collections.ObservableList;
import javafx.event.ActionEvent;
import javafx.fxml.FXML;
import javafx.fxml.Initializable;
import javafx.scene.control.Menu;
import javafx.scene.control.MenuItem;
import javafx.scene.control.TableColumn;
import javafx.scene.control.TableView;
import javafx.scene.control.cell.PropertyValueFactory;
import tn.edu.esprit.sigma.client.delegate.FlightServicesDelegate;
import tn.edu.esprit.sigma.utils.ControlledScreen;
import tn.edu.esprit.sigma.utils.Main;
import tn.edu.esprit.sigma.utils.ScreensController;

public class passengerController implements Initializable, ControlledScreen {
	@FXML
	private Menu btn_home;
	@FXML
	private MenuItem btn_showFlights;
	@FXML
	private MenuItem btn_meals;
	@FXML
	private MenuItem btn_car;
	@FXML
	private MenuItem btn_register;
	@FXML
	private Menu btn_maps;
	@FXML
	private Menu btn_about;
	@FXML
	private TableView tbl_flights;
	@FXML
	private TableColumn cl_flights;
	@FXML
	private TableColumn cl_depaturedate;
	@FXML
	private TableColumn cl_ArrivalDate;
	@FXML
	private TableColumn cl_destination;

	// Event Listener on Menu[#btn_home].onAction
	@FXML
	public void showHome(ActionEvent event) {
		// TODO Autogenerated
	}

	// Event Listener on MenuItem[#btn_showFlights].onAction
	@FXML
	public void showFlights(ActionEvent event) {
		Main.mainCantainer.loadscreen(Main.g_pageauthentificationtID, Main.g_pageauthentificationFile);
		Main.mainCantainer.setScreen(Main.g_pageauthentificationtID);
	}

	// Event Listener on MenuItem[#btn_meals].onAction
	@FXML
	public void showMeals(ActionEvent event) {
		// TODO Autogenerated
	}

	// Event Listener on MenuItem[#btn_car].onAction
	@FXML
	public void showCar(ActionEvent event) {
		// TODO Autogenerated
	}

	// Event Listener on MenuItem[#btn_register].onAction
	@FXML
	public void Register(ActionEvent event) {
		Main.mainCantainer.loadscreen(Main.g_pageRegisterrID, Main.g_pageRegisterrFile);
		Main.mainCantainer.setScreen(Main.g_pageRegisterrID);
	}
	// Event Listener on Menu[#btn_maps].onAction

	@FXML
	public void showMapAirport(ActionEvent event) {
//		Main.mainCantainer.loadscreen(Main.g_mapID, Main.g_mapFile);
//		Main.mainCantainer.setScreen(Main.g_mapID);
	}

	// Event Listener on Menu[#btn_about].onAction
	@FXML
	public void showAbout(ActionEvent event) {
		// TODO Autogenerated
	}

	@Override
	public void SetScreenParent(ScreensController screenpage) {
		// TODO Auto-generated method stub

	}

	@Override
	public void initialize(URL location, ResourceBundle resources) {
		ArrayList<Flight> flights = (ArrayList<Flight>) FlightServicesDelegate.doFindAllFlights();
		ObservableList<Flight> data = FXCollections.observableArrayList(flights);
		for (Flight flight : flights) {
			cl_flights.setCellValueFactory(new PropertyValueFactory<Flight, String>("id"));
			cl_depaturedate.setCellValueFactory(new PropertyValueFactory<Flight, String>("dateDeparture"));
			cl_ArrivalDate.setCellValueFactory(new PropertyValueFactory<Flight, String>("dateArrival"));
			cl_destination.setCellValueFactory(new PropertyValueFactory<Flight, String>("destination"));
			tbl_flights.setItems(data);
		}
	}

}
